# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checking_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('che_date', models.DateField()),
                ('che_statu', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '考勤',
                'verbose_name': '考勤',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dep_tele', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': '部门',
                'verbose_name': '部门',
            },
        ),
        migrations.CreateModel(
            name='Enployee',
            fields=[
                ('enp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('enp_name', models.CharField(max_length=10)),
                ('enp_wage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sta_date', models.DateField()),
                ('end_date', models.DateField()),
                ('enp_laor', models.IntegerField()),
                ('enp_grade', models.IntegerField()),
                ('enp_depa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department')),
            ],
            options={
                'verbose_name_plural': '员工',
                'verbose_name': '员工',
            },
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '后勤',
                'verbose_name': '后勤',
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6)),
                ('insu', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=6)),
                ('real_wage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('enp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Enployee')),
            ],
            options={
                'verbose_name_plural': '金钱',
                'verbose_name': '金钱',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('pro_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department')),
            ],
            options={
                'verbose_name_plural': '职业',
                'verbose_name': '职业',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Enployee')),
                ('to_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profession')),
            ],
            options={
                'verbose_name_plural': '升迁',
                'verbose_name': '升迁',
            },
        ),
        migrations.CreateModel(
            name='Retire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension', models.DecimalField(decimal_places=2, max_digits=6)),
                ('enp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Enployee')),
            ],
            options={
                'verbose_name_plural': '退休',
                'verbose_name': '退休',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('effect', models.DecimalField(decimal_places=2, max_digits=3)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('money', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '销售',
                'verbose_name': '销售',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('tra_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tra_plan', models.TextField()),
                ('tra_statu', models.BooleanField(default=False)),
                ('tra_result', models.TextField()),
            ],
            options={
                'verbose_name_plural': '培训',
                'verbose_name': '培训',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effect', models.DecimalField(decimal_places=2, max_digits=3)),
                ('consum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '车间',
                'verbose_name': '车间',
            },
        ),
        migrations.AddField(
            model_name='enployee',
            name='enp_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profession'),
        ),
        migrations.AddField(
            model_name='checking_in',
            name='enp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Enployee'),
        ),
    ]
