# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('aca_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('aca_tele', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': '1.学院',
                'verbose_name': '1.学院',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('apa_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room_num', models.IntegerField()),
                ('bed_num', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '4.宿舍',
                'verbose_name': '4.宿舍',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('gra_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': '3.班级',
                'verbose_name': '3.班级',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('maj_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('aca_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Academy')),
            ],
            options={
                'verbose_name_plural': '2.专业',
                'verbose_name': '2.专业',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('cre_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '7.公告',
                'verbose_name': '7.公告',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_type', models.CharField(max_length=4)),
                ('message', models.TextField()),
                ('statu', models.BooleanField(default=False)),
                ('cre_date', models.DateTimeField(auto_now=True)),
                ('fin_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '8.维修',
                'verbose_name': '8.维修',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room_num', models.IntegerField()),
                ('apa_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Apartment')),
            ],
            options={
                'verbose_name_plural': '5.房间',
                'verbose_name': '5.房间',
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '6.学生', 'verbose_name_plural': '6.学生'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='stu_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='statu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='stu_id',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repair',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Room'),
        ),
        migrations.AddField(
            model_name='grade',
            name='maj_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Major'),
        ),
        migrations.AddField(
            model_name='student',
            name='gra_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Room'),
            preserve_default=False,
        ),
    ]
